name: Release

on:
  push:
    tags:
      - 'v*'  # 当 push 的 tag 符合 "v*" 模式时触发构建
  workflow_dispatch:  # 手动触发

jobs:
  tauri-build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]  #
        node-version: [18]  #  Node.js 18

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Install system dependencies on Ubuntu
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y libwebkit2gtk-4.0-dev libgtk-3-dev

      - name: Install dependencies
        run: |
          npm install -g pnpm
          pnpm install

      - name: Build app
        run: pnpm tauri build

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            src-tauri/target/release/bundle/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
